### ISSUE TITLE
Example.browser-to-browser not working with Ubuntu bulseye

### ISSUE THREAD

**Issue by KirillKozhin** [fluencelabs/examples#198]
hi

*I did comands*
1 git clone https://github.com/fluencelabs/examples
2 cd examples/quickstart/1-browser-to-browser
3 npm install

***
> getting-started-browser@0.1.0 postinstall /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser
> copy-avm-public public

ensure directory exists:  /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser/public
copying AVM wasm
from:  /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser/node_modules/@fluencelabs/avm/dist/avm.wasm
to:  /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser/public/avm.wasm
done!
ensure directory exists:  /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser/public
copying avm runner script
from:  /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser/node_modules/@fluencelabs/avm-runner-background/dist/runnerScript.web.js
to:  /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser/public/runnerScript.web.js
done!
ensure directory exists:  /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser/public
copying marine-js wasm
from:  /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser/node_modules/@fluencelabs/marine-js/dist/marine-js.wasm
to:  /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser/public/marine-js.wasm
done!
npm WARN @testing-library/user-event@12.8.3 requires a peer of @testing-library/dom@>=7.21.4 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN jest-puppeteer@6.1.0 requires a peer of puppeteer@>= 1.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN native-fetch@3.0.0 requires a peer of node-fetch@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 1911 packages in 15.762s

190 packages are looking for funding
  run `npm fund` for details

found 23 vulnerabilities (10 low, 13 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
***
4 npm run compile-aqua
***
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compile-aqua' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'precompile-aqua', 'compile-aqua', 'postcompile-aqua' ]
5 info lifecycle getting-started-browser@0.1.0~precompile-aqua: getting-started-browser@0.1.0
6 info lifecycle getting-started-browser@0.1.0~compile-aqua: getting-started-browser@0.1.0
7 verbose lifecycle getting-started-browser@0.1.0~compile-aqua: unsafe-perm in lifecycle true
8 verbose lifecycle getting-started-browser@0.1.0~compile-aqua: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/kirill/fluence/test/examples/quickstart/1-browser-to-browser/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle getting-started-browser@0.1.0~compile-aqua: CWD: /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser
10 silly lifecycle getting-started-browser@0.1.0~compile-aqua: Args: [ '-c', 'aqua -i ./aqua/ -o ./src/_aqua' ]
11 silly lifecycle getting-started-browser@0.1.0~compile-aqua: Returned: code: 1  signal: null
12 info lifecycle getting-started-browser@0.1.0~compile-aqua: Failed to exec compile-aqua script
13 verbose stack Error: getting-started-browser@0.1.0 compile-aqua: `aqua -i ./aqua/ -o ./src/_aqua`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid getting-started-browser@0.1.0
15 verbose cwd /home/kirill/fluence/test/examples/quickstart/1-browser-to-browser
16 verbose Linux 5.13.0-35-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "compile-aqua"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error getting-started-browser@0.1.0 compile-aqua: `aqua -i ./aqua/ -o ./src/_aqua`
22 error Exit status 1
23 error Failed at the getting-started-browser@0.1.0 compile-aqua script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
***

**Comment by boneyard93501** [comment]
looks like a node and npm version mismatch. closing for now.
