### ISSUE TITLE
Failed to run browser-to-browser example in the devcontainer.

### ISSUE THREAD

**Issue by vi** [fluencelabs/examples#40]
I trying to run browser-to-browser example in devcontainer (without vscode), but it fails.

1. I pulled `fluencelabs/devcontainer` (image ID  8345668a42fe   )
2. I started it: `docker run --rm -it fluencelabs/devcontainer`. Working directory is the root directory.
3. I executed `git clone --depth 1 https://github.com/fluencelabs/examples.git examples`, the first line from `/download_examples.sh` script. Current commit  013ceb6d373525f71a8e4d9fbfb572fde325603d.
4. In directory `/examples/quickstart/1-browser-to-browser` I issued `npm install`, as recommended by [the tutorial](https://doc.fluence.dev/docs/quick-start/1.-browser-to-browser-1).
5. The command finished successfully (exit code 0), albeit with warnings and update notifications.
6. I issued `npm start`, as recommended by the tutorial.
7. I saw `Starting the development server...`, then 
       
       Failed to compile.
       
       ./src/App.tsx
       Module not found: Can't resolve './_aqua/getting-started' in '/examples/quickstart/1-browser-to-browser/src'
        
Expected: it starts listening development server on port 3000, as per the tutorial.

8. As a workaround attempt, I exited (Ctrl+C) the `npm start` and did this command: `mkdir src/_aqua && aqua-cli --input aqua/getting-started.aqua --output src/_aqua` (not taken from the tutorial). It had finished successfully and produced `getting-started.ts` file, but `npm start` still does not work:

       Failed to compile.
       
       ./src/App.tsx
       Attempted import error: 'registerHelloPeer' is not exported from './_aqua/getting-started'.

---

Does devcontainer and tutorial really support VSCode-less experimentation?

**Comment by boneyard93501** [comment]
run `npm run compile-aqua` before `npm start`. for the browser pop-up to work, you need to run it in vscode or make adjustments to the devcontainer config.

**Comment by vi** [comment]
`npm run compile-aqua` indeed made `npm start` work. The page that is depicted in the tutorial now shows up at http://127.0.0.1:3000/.

Clicking any "Connect" button in the "Pick a relay" menu however fails and produces the following message in Firefox's dev console:

```
The script from “http://127.0.0.1:3000/runnerScript.web.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
127.0.0.1:3000
SyntaxError: expected expression, got '<'
```

The script's URL serves index page instead of the script.

The file is present in project directory:

```
$ find | grep runnerScript.web.js
./node_modules/@fluencelabs/avm-runner-background/dist/runnerScript.web.js
./node_modules/@fluencelabs/avm-runner-background/runner-scripts/runnerScript.web.js
```

**Comment by boneyard93501** [comment]
if you give it long enough, about 10_000ms to be precise, you'll see and error message informing you that the connection isn't happening.
```
Peer initialization failed Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at spawn.js:29:1
```
which is due to an outdated npm version. 
 
`root@6a6fc047f75f:/workspaces/devcontainer# npm install -g npm@latest` and then update your packages. 

we are just about to send devcontainer to archive pastures and you're probably better off to just run the examples without it.  

sorry for the detours and frustrations.

**Comment by vi** [comment]
`npm install -g npm@latest` + rerunning other npm commands resolved the issue. Now the demo works and two browser tabs can exchange hello messages.

---

> we are just about to send devcontainer to archive pastures and you're probably better off to just run the examples without it.

Will quickstart tutorial be updated to accommodate it?

**Comment by boneyard93501** [comment]
in short order. fyi @coder11
